
#source_repo https://github.com/alist-org/alist.git
#target_repo git@github.com:mzbgf/auto-clone.git

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          mkdir -p ~/.ssh
          key=$PWD/sshkey
          log=$PWD/actlogs.txt
          echo "begin" > $log
          echo "${{secrets.GITEE_RSA_PRIVATE_KEY}}" > $key
          echo "github:" > $log
          ssh -T git@github.com | tee -a $log
          echo "gitlab:" > $log
          ssh -T git@gitlab.com | tee -a $log
          echo "gitee:" > $log
          ssh -T git@gitee.com | tee -a $log
          git clone https://github.com/wearerequired/git-mirror-action
          git clone https://github.com/mzbgf/auto-clone
          file=$PWD/auto-clone/sync.conf
          cd ./git-mirror-action

      - name: Sync repositories 
        run: |
          egrep -v "^#|^$" $file | while read line; do
            source_repo=$(echo $line | awk '{print $1}') 
            target_repo=$(echo $line | awk '{print $2}')
            echo "Syncing $source_repo to $target_repo" | tee -a $log
            docker run --rm -e "SSH_PRIVATE_KEY=$(cat $key)" $(docker build -q .) "$source_repo" "$target_repo"
          done
          echo "view_log:"
          cat $log


