
#source_repo https://github.com/alist-org/alist.git
#target_repo git@github.com:mzbgf/auto-clone.git

on:
  schedule:
    - cron: '*/30 * * * *'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync repositories 
        run: |
          file=sync.conf
          egrep -v "^#|^$" $file | while read line; do
            source_repo=$(echo $line | awk '{print $1}')
            target_repo=$(echo $line | awk '{print $2}')
            echo "Syncing $source_repo to $target_repo"
            uses: wearerequired/git-mirror-action@master
            env: SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
            with:
              source-repo: $source_repo
              destination-repo: $target_repo
          done


