
#source_repo https://github.com/alist-org/alist.git
#target_repo git@github.com:mzbgf/auto-clone.git

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check
        run: |
          echo "${{secrets.GITEE_RSA_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          git clone https://github.com/wearerequired/git-mirror-action
          cd git-mirror-action

      - name: Sync repositories 
        run: |
          file=../sync.conf
          egrep -v "^#|^$" $file | while read line; do
            source_repo=$(echo $line | awk '{print $1}')
            target_repo=$(echo $line | awk '{print $2}')
            echo "Syncing $source_repo to $target_repo"
            docker run --rm -e "SSH_PRIVATE_KEY=$(cat ~/.ssh/id_rsa)" $(docker build -q .) "$source_repo" "$target_repo"
          done


