
#source_repo https://github.com/alist-org/alist.git
#target_repo git@github.com:mzbgf/auto-clone.git

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync repositories
        run: |
          mkdir -p .ssh
          echo "" > ${PWD}/.ssh/id_rsa
          chmod 600 ${PWD}/.ssh/id_rsa
          echo "${{secrets.RSA_PRIVATE_KEY}}" > ${PWD}/.ssh/id_rsa
          echo "begin test"
          echo "github:"
          ssh -T git@github.com || true
          echo "gitlab:"
          ssh -T git@gitlab.com || true
          echo "gitee:"
          ssh -T git@gitee.com || true
          
          git clone https://github.com/wearerequired/git-mirror-action || true
          git clone https://github.com/mzbgf/auto-clone || true
          
          file=${PWD}/auto-clone/sync.conf
          
          echo ""
          echo "begin Cloning..."
          cd ./git-mirror-action
          egrep -v "^#|^$" $file | while read line; do
            source_repo=$(echo $line | awk '{print $1}') 
            target_repo=$(echo $line | awk '{print $2}')
            echo "Syncing $source_repo to $target_repo"
            docker run --rm -e "SSH_PRIVATE_KEY=${{secrets.RSA_PRIVATE_KEY}}" $(docker build -q .) "$source_repo" "$target_repo" || true
          done
          cd ..
          tree .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: runner-diagnostic-logs


