
#source_repo https://github.com/alist-org/alist.git
#target_repo git@github.com:mzbgf/auto-clone.git

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync repositories
        run: |
          mkdir -p ~/.ssh
          log=$PWD/actlogs.txt
          echo "${{secrets.GITEE_RSA_PRIVATE_KEY}}" > id_rsa
          chmod 600 id_rsa
          eval "$(ssh-agent -s)" || true
          ssh-add id_rsa || true
          echo "begin" > actlogs.txt
          ssh -T git@github.com | tee -a actlogs.txt
          echo "gitlab:" > actlogs.txt
          ssh -T git@gitlab.com | tee -a actlogs.txt
          echo "gitee:" > actlogs.txt
          ssh -T git@gitee.com | tee -a actlogs.txt
          
          git clone https://github.com/wearerequired/git-mirror-action
          git clone https://github.com/mzbgf/auto-clone
          
          file=$PWD/auto-clone/sync.conf
          cd ./git-mirror-action

          egrep -v "^#|^$" $file | while read line; do
            source_repo=$(echo $line | awk '{print $1}') 
            target_repo=$(echo $line | awk '{print $2}')
            echo "Syncing $source_repo to $target_repo" | tee -a ../actlogs.txt
            docker run --rm -e "SSH_PRIVATE_KEY=${{secrets.GITEE_RSA_PRIVATE_KEY}}" $(docker build -q .) "$source_repo" "$target_repo" || true
          done
          
          echo "view_log:"
          cat ../actlogs.txt
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ../actlogs.txt


